# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 876ea713c6785db953a2d702db5f5cd5d49d6f39c176146ab2b6135572579d24cf21aa44e2909dbf0fa939dab152ed039c1e06e5e6ccaa37e43357b8706f9d0a

test:
  secret_key_base: 984c5759cc432c19db8d95313ed6a7fc32efaef3746578943f92ce68d4be83b08f5dd30083121270413af37504c08373e46acac05022bafe97825744667a2696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
